### ISSUE TITLE
Build Nostr-Abbot (NAb) Server

### ISSUE THREAD

**Issue by aidadiaz9** [ATLBitLab/open-abbot#4]
~~**Due date = 10/15/23**~~

**Comment by bnonni** [comment]
**Due date = 10/16/23 (updated)**

**Comment by bnonni** [comment]
See #3 for plan

**Comment by bnonni** [comment]
https://github.com/ATLBitLab/nostr-meetup-relay/tree/main

**Comment by bnonni** [comment]
Closing this issue given the progress here: https://github.com/ATLBitLab/open-abbot/issues/3#issuecomment-1773796004
